---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lunch-messenger
spec:
  schedule: "0 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lunch-messenger
            image: ghcr.io/rcanderson23/lunch-messenger:latest
            envFrom:
            - secretRef:
                name: pushover-credentials
          restartPolicy: OnFailure
---

